//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JecPizza.Content.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JecPizza.Content.Languages.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ソフトについて.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 確定.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アカウント.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商品追加.
        /// </summary>
        public static string AddGoods {
            get {
                return ResourceManager.GetString("AddGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商品管理.
        /// </summary>
        public static string AddProduct {
            get {
                return ResourceManager.GetString("AddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 予約追加する.
        /// </summary>
        public static string AddRes {
            get {
                return ResourceManager.GetString("AddRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 予算.
        /// </summary>
        public static string Budget {
            get {
                return ResourceManager.GetString("Budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 月ごとに.
        /// </summary>
        public static string ByMonth {
            get {
                return ResourceManager.GetString("ByMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to キャンセル.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _閉じる.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ダッシュボード.
        /// </summary>
        public static string Dash {
            get {
                return ResourceManager.GetString("Dash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日にち.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 削除.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配達管理.
        /// </summary>
        public static string Delivery {
            get {
                return ResourceManager.GetString("Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 編集.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _英語.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 編集失敗!.
        /// </summary>
        public static string ErEdit {
            get {
                return ResourceManager.GetString("ErEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _閉じる.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _ファイル.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商品名.
        /// </summary>
        public static string GName {
            get {
                return ResourceManager.GetString("GName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商品グループID.
        /// </summary>
        public static string GoodsGrId {
            get {
                return ResourceManager.GetString("GoodsGrId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 予約済み.
        /// </summary>
        public static string IsRes {
            get {
                return ResourceManager.GetString("IsRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _日本語.
        /// </summary>
        public static string Japanese {
            get {
                return ResourceManager.GetString("Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _言語.
        /// </summary>
        public static string Lang {
            get {
                return ResourceManager.GetString("Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名前.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新商品.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to お知らせ.
        /// </summary>
        public static string Notif {
            get {
                return ResourceManager.GetString("Notif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _商品 CSVファイルを開く.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスワード.
        /// </summary>
        public static string Pass {
            get {
                return ResourceManager.GetString("Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 人数.
        /// </summary>
        public static string People {
            get {
                return ResourceManager.GetString("People", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 電話番号.
        /// </summary>
        public static string PhoneN {
            get {
                return ResourceManager.GetString("PhoneN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 人数.
        /// </summary>
        public static string PNum {
            get {
                return ResourceManager.GetString("PNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 価格.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to おすすめ品.
        /// </summary>
        public static string Rec {
            get {
                return ResourceManager.GetString("Rec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 予約管理.
        /// </summary>
        public static string Reservation {
            get {
                return ResourceManager.GetString("Reservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _ロシア語.
        /// </summary>
        public static string Russian {
            get {
                return ResourceManager.GetString("Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 売上.
        /// </summary>
        public static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本日の予算を設定する.
        /// </summary>
        public static string Sb {
            get {
                return ResourceManager.GetString("Sb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 検索.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本日の予算を入力してください.
        /// </summary>
        public static string SetBudget {
            get {
                return ResourceManager.GetString("SetBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _設定.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 追加されました.
        /// </summary>
        public static string Suc {
            get {
                return ResourceManager.GetString("Suc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 編集成功!.
        /// </summary>
        public static string SucEdit {
            get {
                return ResourceManager.GetString("SucEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名字.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to テーブル番号.
        /// </summary>
        public static string TableNum {
            get {
                return ResourceManager.GetString("TableNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本日の売上予算統計.
        /// </summary>
        public static string TBI {
            get {
                return ResourceManager.GetString("TBI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 電話番号.
        /// </summary>
        public static string Tel {
            get {
                return ResourceManager.GetString("Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JecPizzaアドミニストレータ.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to トッピング有無.
        /// </summary>
        public static string Topping {
            get {
                return ResourceManager.GetString("Topping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 予約表を更新する.
        /// </summary>
        public static string URT {
            get {
                return ResourceManager.GetString("URT", resourceCulture);
            }
        }
    }
}
